server:
  port: 8080
  error:
    path: /error

spring:
  application:
    name: EveryMeal-server-main
  profiles:
    include: secret
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://everymeal-rds.cvd1711aoesu.ap-northeast-2.rds.amazonaws.com:3306/everymeal?characterEncoding=UTF-8&useUnicode=true&serverTimezone=Asia/Seoul
    username: everydb
    password: everymeal123!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        default_batch_fetch_size: 10
    open-in-view: false
    show-sql: true

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  swagger-ui:
    path: /docs
    groups-order: DESC
    doc-expansion: none
  api-docs:
    groups:
      enabled: true
    enabled: true