spring:
  datasource:
    url: jdbc:mysql://everymeal-rds.cvd1711aoesu.ap-northeast-2.rds.amazonaws.com:3306/everymeal?characterEncoding=UTF-8&useUnicode=true&serverTimezone=Asia/Seoul
    username: everydb
    password: everymeal123!!