server:
  port: 8080
  error:
    path: /error

spring:
  application:
    name: EveryMeal-server-main
  profiles:
    include: secret
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        default_batch_fetch_size: 10
    open-in-view: false
    show-sql: true

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  swagger-ui:
    path: /docs
    groups-order: DESC
    doc-expansion: none
  api-docs:
    groups:
      enabled: true
    enabled: true