name: SonarCloud
on:
  pull_request:
    branches:
    - develop
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Spotless check
        run: ./gradlew spotlessCheck
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Start MySQL
        uses: samin/mysql-action@v1.3
        with:
          host port: 3303
          container port: 3303
          mysql database: 'test_db'
          mysql user: 'test'
          mysql password: 'test_pw'

      - name: Make application-secret.yml
        run: |
          cd ./src/main/resources
          touch ./application-secret.yml
          echo "${{ secrets.PROPERTIES_SECRET }}" > ./application-secret.yml
        shell: bash

      - name: Make test application.yml
        run: |
          mkdir -p src/test/resources
          cd ./src/test/resources
          touch ./application.yml
          echo "${{ secrets.PROPERTIES_SECRET_TEST }}" > ./application.yml
        shell: bash

      - name: Build and analyze
        run: ./gradlew test sonar --info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}